server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:live_betting_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  hikari:
    maximum-pool-size: 50
    connection-timeout: 30000
    idle-timeout: 60000
    max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false